### ISSUE TITLE
Idea: Nullable Model Trait

### ISSUE THREAD

**Issue by rscafi** [esensi/model#18]
Problem:
> I had problems trying to insert data into the database when I had foreign key fields that could be null. By default, they are inserted as empty values and that would cause an error as the value would not make reference to the other table.

Something like proposed here:
http://laravelsnippets.com/snippets/set-fields-to-null-instead-of-empty-value-to-avoid-problems-with-nullable-foreign-keys

**Comment by rscafi** [comment]
Another approach that I prefer, (I can't remeber where I saw it to give the proper credits) would be having a `$nullable` array property, and only set null on these fields.
```php
    /**
     * The attributes that should be set to null if represented by falsy values.
     *
     * @var array
     */
    protected $nullable = [];

    /**
     * Listen for save event
     */
    protected static function boot()
    {
        static::saving(function ($model)
        {
            self::setNullables($model);
        });

        parent::boot();
    }

    /**
     * Set empty nullable fields to null
     *
     * @param object $model
     */
    protected static function setNullables($model)
    {
        foreach ($model->nullable as $field)
        {
            if (empty($model->{$field}))
            {
                $model->{$field} = null;
            }
        }
    }
```

I can addapt it to a Trait, create tests and send a PR if you guys want.

**Comment by dalabarge** [comment]
You might find that your idea could just make use of adding a `juggleNull` method to the `JugglingModelTrait`. It's not quite the same thing as you describe but by using the juggle method you could convert empty values to a `null` type and leave non-empty values alone. This probably wouldn't work well for boolean values which need to default to `null` though.

Yes, please do up a PR. Note that we don't use the `boot` method directly but use the dynamic `bootNullableModelTrait` methods which then offload the calls like `static::saving` to an `NullableModelObserver` class. So likely you'll want to call the classes/traits:

```
Esensi\Model\Contracts\NullableModelInterface
Esensi\Model\Traits\NullableModelTrait
Esensi\Model\Observers\NullableModelObserver
```
And you'll want to add this trait to the default `Model` class. There are corresponding tests that we normally write for this sort of thing and we encourage people do those too. That said, if there's any part your aren't proficient enough to develop please send the PR along and we'll take care of the rest. Also feel free to open the PR early for feedback early on.

**Comment by dalabarge** [comment]
The `null` juggling type now makes it possible to easily check for the `empty` case and assign `null` as the default value though usually it will require a model reset if you want to do it during a fill operation from `Request` where empty strings are suppose to be `null`.
