### ISSUE TITLE
Lumen 5 support

### ISSUE THREAD

**Issue by Cyrille37** [esensi/model#20]
Hey there,
Does it works with Lumen 5 ?

I did a simple CRUD (like documentation) but it seems to not validate model on save().

Cheers

**Comment by malinow** [comment]
Hey @Cyrille37,

We haven't tested Esensi/Model with Lumen -- it's possible it doesn't work.

If you figure out what's going on, let us know! Happy to accept a pull request with a fix, or to update the docs to confirm it can't work with Lumen as-is.

Thanks!

**Comment by Cyrille37** [comment]
Hey,

I did some mistake in $rules array and now it works !
So we perhaps could say that Esensi\Model works with Lumen !
;-)

You can close this bug, and excuse me for the noise.
Cheers

**Comment by malinow** [comment]
No problem, glad you figured it out! :grinning: 
MM
