### ISSUE TITLE
Optional polymorphic relationship throws fatal error

### ISSUE THREAD

**Issue by Einkoro** [esensi/model#21]
Using the example from the documentation (http://laravel.com/docs/5.0/eloquent#polymorphic-relations) and checking the morphTo relation if imageable_id and imageable_type are NULL in the database:
```
> $photo = Photo::find(1);
// object(Photo)(
//   'incrementing' => true,
//   'timestamps' => true,
//   'exists' => true
// )
[5] > $photo->imageable;
PHP Fatal error:  Class '' not found in /home/vagrant/Projects/Varar/vendor/esensi/model/src/Traits/RelatingModelTrait.php on line 290
```
Shouldn't this return null? I would expect the behaviour to be the same as belongsTo with a null foreign key.

**Comment by dalabarge** [comment]
It looks like a little bit of code has changed in the underlying Eloquent model and we'll need to figure out what the appropriate backtrace is to get to the called class. I think what is happening is that it's getting the wrong traceback and is an empty string instead of null which would have been caught above. We'll need to time to sort it out and we appreciate you bringing it to our attention.

Can you maybe setup a public fork of a fully functional example default Laravel install but with Esensi and a test case of the model I can clone and tinker with? That would help speed things up. I'll see about providing a regression test too so we can easily catch this in the future.

**Comment by Einkoro** [comment]
Setting up a Laravel 5.1 instance right now. Little bit different as I was working on 4.2 but it looks like the morphTo code hasn't changed from what I see so far.

Gist of the test, seeder, migrations and models as composer is taking awhile to checkout everything: https://gist.github.com/Einkoro/79918cf13c327579fa9b

**Comment by Einkoro** [comment]
Looks like this might actually be fixed somewhere in newer versions of Eloquent although I see no mention of it in tickets anywhere – ``$this->$type`` is coming back as NULL with Laravel 5.0.22. Are you still supporting the 4.2 branch? 

Unrelated note it looks like composer.json needs updating to install esensi/model under 5.1

**Comment by dalabarge** [comment]
I was unaware you were using a 4.2 branch. We are not actively supporting 4.2 so if you manage to figure out a back port please submit a PR so we can help others out. Can you post a link to the Laravel 4.2 commit for Model and the corresponding fix commit from 5? I might be able to patch it up quickly or at least point you in the right direction.

**Comment by Einkoro** [comment]
Haven't found any commit messages or tickets of relevance other than one ticket with no linked pull request or commits closed ages ago without comments. I'll look through the history and see if anything changed in morphTo that can be back ported. 

----
Jan Pingel
jan.pingel@me.com
+1 (778) 678 2248

**Comment by Einkoro** [comment]
Looks like it was fixed here in Eloquent: https://github.com/laravel/framework/commit/7dca817417ef3db4812814b61e480563bb45cf0d

Looks easy enough to back port to 4.2 if it wasn't locked to security fixes only.

**Comment by dalabarge** [comment]
@Einkoro this bug appears to be a 4.2 bug which didn't receive a fix until it was merged in 5.0.30. While there are thousands of other bug fix reasons to upgrade from 4.2 to 5.0 I realize it is a major upgrade and a lot of clients won't see the light on why it's so important. I totally get the fact that Laravel is tightly controlled and the only movement is forward up till the recent LTS release. We've had plenty of our own PRs, cherry picks, and issues closed for the same reasons. So I think your solution is to use a custom MorphTo relationship class. Something like the following should do the trick:

Create a custom `MorphTo` relation class by extending the base one and then adding the missing `getResults()` method. You might also want to consider adding the missing [code found here](https://github.com/laravel/framework/commit/33622bc32c5f0bad2029fe1a762a41d19e25e7a2) too!

```php
<?php namespace App\Models\Relations;

use Illuminate\Database\Eloquent\Relations\MorphTo as BaseMorphTo;

class MorphTo extends BaseMorphTo {

    /**
     * Get the results of the relationship.
     *
     * @return mixed
     */
    public function getResults()
    {
        if ( ! $this->otherKey) return;
        return $this->query->first();
    }
}
```

Then you incorporate this new model into a trait override for the `morphTo()` method:

```php
<?php namespace App\Models\Traits;

// You use this custom relationship in this
// trait all other code is the same.
use App\Models\Relations\MorphTo;

trait RelatingMorphToTrait {
    
    /**
     * Define an polymorphic, inverse one-to-one or many relationship.
     *
     * @param  string $name
     * @param  string $type
     * @param  string $id
     * @return \App\Models\Relations\MorphTo
     */
    public function morphTo( $name = null, $type = null, $id = null )
    {
        // If no name is provided, we will use the backtrace to get the function name
        // since that is most likely the name of the polymorphic interface. We can
        // use that to get both the class and foreign key that will be utilized.
        if (is_null($name))
        {
            list(, $caller, $backtrace) = debug_backtrace(false);
            // Use custom relationship bindings
            if ($backtrace['function'] == 'callRelationship')
            {
                $relation = $backtrace['args'][0];
            }
            // or default to the Eloquent bindings
            else
            {
                $relation = $caller['function'];
            }
            $name = snake_case($relation);
        }
        list($type, $id) = $this->getMorphs($name, $type, $id);
        // If the type value is null it is probably safe to assume we're eager loading
        // the relationship. When that is the case we will pass in a dummy query as
        // there are multiple types in the morph and we can't use single queries.
        if ( is_null($class = $this->$type) )
        {
            return new MorphTo(
                $this->newQuery(), $this, $id, null, $type, $name
            );
        }
        // If we are not eager loading the relationship we will essentially treat this
        // as a belongs-to style relationship since morph-to extends that class and
        // we will pass in the appropriate values so that it behaves as expected.
        else
        {
            $instance = new $class;
            return new MorphTo(
                with($instance)->newQuery(), $this, $id, $instance->getKeyName(), $type, $name
            );
        }
    }

}
```

Then in your model you do something like this:

```php
<?php namespace App\Models;

// Here's where you use your custom trait
use App\Models\Traits\RelatingMorphToTrait;

// Extend the esensi/model like normal
use Esensi\Model\Model;

class Photo extends Model {
    
    // By using this trait you get the backported fixes
    // of your custom MorphTo relation class
    use RelatingMorphToTrait;
}
```

If you aren't extending the default then you'll just need to do some method negotiation with the use of the multiple traits that have the same methods. Additionally you may find that the back trace no longer fits for the actual morphTo() method that we're using for 4.2 in which case you'll need to do your own debugging there. If you get all this working I'm open to a PR to the 0.4 branch where we marked Laravel 4.2 as end of the road.

And of course keep in mind that we are not actively supporting 4.2 as Esensi is getting ready to target the 5.1 LTS release instead so you'll want to start using the latest Laravel on any new projects you might be starting soon. More of our other packages are compatible with 5.x and we have more yet to be released that will also be. I hope this all helps so be sure to let me know what you end up figuring out!

**Comment by Einkoro** [comment]
In the meantime I'm aliasing a fork of the 4.2 branch with the changes cherry picked through composer. I plan to upgrade to 5.1 LTS in the coming months — its just a lot of refactoring on our end and a few packages that aren't compatible I'll need to deal with.

Looks like there is a few other bugs with polymorphic relationships unfortunately and still present in 5.x —specifically eager loading and whereHas not being supported and I had to add a classmap in each model to use morphClass with morphTo to directly create records not attached to another model.

**Comment by dalabarge** [comment]
@Einkoro thank you for the background information. If you think this is a non-issue or provides others with enough context for moving forward with 4.2 please feel free to mark this issue as closed.

**Comment by Einkoro** [comment]
If anyone else encounters the same issue they are welcome to fork and alias the 4.2 branch with the change already cherry picked here: https://github.com/Einkoro/framework/tree/4.2

I wouldn't really recommend it for production systems though but its sufficient for a quick temporary work around in the meantime. Relevant composer.json bits:

```
	"repositories": [
		{
			"type": "vcs",
			"url": "http://github.com/einkoro/framework"
		}
	],
	"require": {
		"laravel/framework": "4.2.x-dev as 4.2.17"
	},
```
