### ISSUE TITLE
Remove specific rule?

### ISSUE THREAD

**Issue by divdax** [esensi/model#29]
It is possible to remove a specific rule e.g. ```unset($rules['index'])``` inside a controller without using ```forceSave()```?

**Comment by dalabarge** [comment]
You can set/get/merge/remove rules from the model rules and rulesets using methods in our trait and some in Dwight's underlying trait. Take a look here for some usage: https://github.com/esensi/model/blob/master/src/Traits/ValidatingModelTrait.php#L75-L190

```php
$model = new Model;
$model->removeRules(['index']);
if( ! $model->save() ) {
    // ... throw an exception
}
```

Alternatively you could just check it against another ruleset:

```php
$model = new Model;
$ruleset = 'foo'; // name of ruleset on model
if( $model->isInvalid($ruleset) ) {
    // ... throw an exception
}
$model->forceSave();
```

That said, rulesets are officially deprecated and we'll be suggesting people only validate their models against data integrity vs. form validation as Laravel has great support for form validators already.

**Comment by divdax** [comment]
Thank you @dalabarge! I really like the self model validation.
