### ISSUE TITLE
RelatingModelTrait documentation update

### ISSUE THREAD

**Issue by MarthinusBotha** [esensi/model#32]
Greetings,

The documentation for $relationships inside [Relating Model Trait](https://github.com/esensi/model#relating-model-trait) section needs to be updated.

from: `[ 'morphByMany', 'related', 'name', 'table', 'foreignKey', 'otherKey' ]` 
to:  `[ 'morphedByMany', 'related', 'name', 'table', 'foreignKey', 'otherKey' ]`.
The model relation is called `morphedByMany` not `morphByMany` within laravel's Eloquent Model

Regards,

**Comment by stygiansabyss** [comment]
Can confirm.  It is `morphedByMany` and `morphToMany`.

**Comment by diegocaprioli** [comment]
Thanks a lot @MarthinusBotha and @stygiansabyss . The docs are now fixed.
