### ISSUE TITLE
Feature Request: Cacheable Trait

### ISSUE THREAD

**Issue by sarfraznawaz2005** [esensi/model#40]
It would really awesome if there is also `Cacheable` trait, here is nice and simple one to get the idea from which has neat and simple trait:

https://github.com/rinvex/cacheable

The great thing about above package is that it also supports query cache without tags eg with file storage though it also has support for conventional cache drivers.

I can use the mentioned package but I would love to have one package to rule it all :smile: 

Any plans about this ?

Thanks

**Comment by dalabarge** [comment]
Caching at the model level has a lot of undesirable consequences. I understand in some cases it is very convenient, especially between requests, but it's also a lot of "magic" that can lead to very difficult to spot, test, and debug code conditions. Esensi entertained the notion and would consider a PR that essentially wrapped perhaps this package you linked to in an API consistent with the other esensi/model traits. The team has not pursued it as our experience is that caching at the model level is more of an anti-pattern when dealing with an active record model.

Caching at the repository level or at a level above the model anyway is a very reasonable approach and allows for better injection and control over the caching driver, mechanics, and properly decouples the concern from the model's queries being cached. It also lets you easily do app-level, model caching so as to avoid repeated reads for the same model or collection during a single request. It is a very cumbersome thing to do within Laravel and so to that extent there are great abstractions that you could create to make it more convenient. A proxy for example could be created, allowing insert/update/select/delete queries to be individually passed through (un)cached by mimicking the behavior of the underlying models but through a caching veneer, if you will. The same rinvex authors also have another package for this which includes caching at the repository level. If you use that code base for caching model's I'd suggest you check out their repository layer instead. Esensi also has this in [`esensi/core`](http://github.com/esensi/model) though Esensi only has in-memory caching of models and not queries within our repository classes.

So it doesn't look like we'll have one package to rule them all without a bit of community involvement so send us PRs if you want and we will include them despite our own individual reservations about their appropriate usage.
