### ISSUE TITLE
How to specife attribute names for validation errors?

### ISSUE THREAD

**Issue by make-it-git** [esensi/model#46]
Let's say, I have

```
protected $rules = [
    'name' => 'required|string|max:256',
];
```

and I want to show error as "Please specify your name" for "required" rule and "Name must be at most 256 characters long" for "max:256" rule.

Is is possible?

**Comment by dalabarge** [comment]
You can customize all rule validation messages within `resources/lang/en/validation.php` following standard Laravel conventions. If you need to customize for a particular model then you need to look at the documentation for the underlying `watson/validating` package: https://github.com/dwightwatson/validating#validation-messages
